site_name: JetCo
site_url: https://jetco.developerstring.com/
site_dir: .
repo_url: https://github.com/developerchunk/JetCo
repo_name: developerchunk/JetCo

nav:
  - Home: index.md
  - Guide:
    - Overview: guide/jetco-ui/jetco-ui.md
    - Bar Charts: guide/jetco-ui/Bar Chart/ColumnBarChart.md
    - Pie Chart: guide/jetco-ui/Pie Chart/PieChart.md
    - Ticket Card: guide/jetco-ui/Ticket Card/TicketCard.md
    - Curved Card: guide/jetco-ui/Curved Card/CurvedCard.md
    - Steppers: guide/jetco-ui/Steppers/VerticalStepper.md
  - Sample:
    - JetCo-UI: sample/jetco-ui.md
  - Community: community.md
  - License: License.md

theme:
  name: material
  features:
    - toc.integrate
    - content.tabs.link
    - tabs
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode    

plugins:
  # - social
  - search
  

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/developerchunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DeveloperChunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adityashinde1095/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  # for right side table of content
  # - pymdownx.tabbed:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/developerchunk/JetCo?tab=Apache-2.0-1-ov-file#readme"  target="_blank" rel="noopener">Developer Chunk</a>